inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

Airbnb/ClassOrModuleDeclaredInWrongFile:
  Enabled: false

Airbnb/ConstAssignedInWrongFile:
  Enabled: false

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
