inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  TargetRubyVersion: 3.0

Metrics/LineLength:
  Enabled: false

# Ignore Rails-y Airbnb recommendation
Airbnb/ClassOrModuleDeclaredInWrongFile:
  Enabled: false

# Ignore Rails-y Airbnb recommendation
Airbnb/ConstAssignedInWrongFile:
  Enabled: false

# Allow empty examples to stub out specs
RSpec/EmptyExampleGroup:
  Enabled: false

# Allow fake tests to stub out specs
RSpec/ExpectActual:
  Enabled: false

# It just looks nicer
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
